FROM       cyberdojofoundation/scala-2.12.1
MAINTAINER Jon Jagger <jon@jaggersoft.com>

COPY scalatest_2.12-3.0.1.jar /scalatest/
COPY scalactic_2.12-3.0.1.jar /scalatest/

COPY red_amber_green.rb /usr/local/bin
