FROM cyberdojofoundation/java-1.8
MAINTAINER Jon Jagger <jon@jaggersoft.com>

ENV KOTLIN_VERSION=1.1.2-2 \
    KOTLIN_HOME=/usr/share/kotlin

RUN mkdir "${KOTLIN_HOME}"
WORKDIR ${KOTLIN_HOME}

RUN apk add --update bash \
  && apk add --virtual=build-dependencies wget ca-certificates \
  && wget "https://github.com/JetBrains/kotlin/releases/download/v${KOTLIN_VERSION}/kotlin-compiler-${KOTLIN_VERSION}.zip" \
  && unzip "kotlin-compiler-${KOTLIN_VERSION}.zip" \
  && rm "kotlin-compiler-${KOTLIN_VERSION}.zip" \
  && apk del build-dependencies \
  && rm -rf /tmp/* /var/cache/apk/*

ENV PATH=${PATH}:${KOTLIN_HOME}/kotlinc/bin
